// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Utfpr.Troca.De.Talentos.Infrastructure.Migrations.Postgre;

namespace Utfpr.Troca.De.Talentos.Infrastructure.Migrations.Postgre.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationsDbContext))]
    [Migration("20211211172952_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UTFPR")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Areas.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idarea")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_area");

                    b.ToTable("area");
                });

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Pessoas.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idpessoa")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnName("campus")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnName("cidade")
                        .HasColumnType("text");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnName("curso")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("dtcadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("estado")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("text");

                    b.Property<long>("UsuarioId")
                        .HasColumnName("idusuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_pessoa");

                    b.ToTable("pessoa");
                });

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Pessoas.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idusuario")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnName("fotoperfil")
                        .HasColumnType("bytea");

                    b.Property<string>("Ra")
                        .IsRequired()
                        .HasColumnName("ra")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("senha")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnName("tipo")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Pessoas.UsuarioArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idusuarioarea")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("_areaId")
                        .HasColumnName("idarea")
                        .HasColumnType("bigint");

                    b.Property<long>("_usuarioId")
                        .HasColumnName("idusuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_usuarioarea");

                    b.HasIndex("_areaId")
                        .HasName("ix_usuarioarea_idarea");

                    b.HasIndex("_usuarioId")
                        .HasName("ix_usuarioarea_idusuario");

                    b.ToTable("usuarioarea");
                });

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Pessoas.Usuario", b =>
                {
                    b.HasOne("Utfpr.Troca.De.Talentos.Domain.Pessoas.Pessoa", null)
                        .WithOne("Usuario")
                        .HasForeignKey("Utfpr.Troca.De.Talentos.Domain.Pessoas.Usuario", "Id")
                        .HasConstraintName("fk_usuario_pessoa_idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Utfpr.Troca.De.Talentos.Domain.Pessoas.UsuarioArea", b =>
                {
                    b.HasOne("Utfpr.Troca.De.Talentos.Domain.Areas.Area", "Area")
                        .WithMany()
                        .HasForeignKey("_areaId")
                        .HasConstraintName("fk_usuarioarea_area_idarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utfpr.Troca.De.Talentos.Domain.Pessoas.Usuario", "Usuario")
                        .WithMany("Areas")
                        .HasForeignKey("_usuarioId")
                        .HasConstraintName("fk_usuarioarea_usuario_idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
